-- MySQL Script generated by MySQL Workbench
-- Sun Aug 22 12:52:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jbikex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jbikex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jbikex` DEFAULT CHARACTER SET utf8 ;
USE `jbikex` ;

-- -----------------------------------------------------
-- Table `jbikex`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`addresses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `number` INT(11) NULL DEFAULT NULL,
  `apt` INT(11) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `zipcode` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `desc1` TEXT NULL DEFAULT NULL,
  `desc2` TEXT NULL DEFAULT NULL,
  `image1` VARCHAR(255) NULL DEFAULT NULL,
  `image2` VARCHAR(255) NULL DEFAULT NULL,
  `image3` VARCHAR(255) NULL DEFAULT NULL,
  `image4` VARCHAR(255) NULL DEFAULT NULL,
  `keywords` TEXT NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `discount` INT(11) NULL DEFAULT NULL,
  `cuotas` INT(11) NULL DEFAULT NULL,
  `activate` INT(11) NULL DEFAULT NULL,
  `brandId` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `brandId` (`brandId` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`brandId`)
    REFERENCES `jbikex`.`brands` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`categoryproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`categoryproducts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `productId` INT(11) NULL DEFAULT NULL,
  `categoryId` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `categoryId` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `categoryproducts_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `jbikex`.`products` (`id`),
  CONSTRAINT `categoryproducts_ibfk_2`
    FOREIGN KEY (`categoryId`)
    REFERENCES `jbikex`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`colors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`colorproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`colorproducts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `productId` INT(11) NULL DEFAULT NULL,
  `colorId` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `colorId` (`colorId` ASC) VISIBLE,
  CONSTRAINT `colorproducts_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `jbikex`.`products` (`id`),
  CONSTRAINT `colorproducts_ibfk_2`
    FOREIGN KEY (`colorId`)
    REFERENCES `jbikex`.`colors` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`genres` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`rols` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `addressId` INT(11) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `rolId` INT(11) NULL DEFAULT NULL,
  `genreId` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `addressId` (`addressId` ASC) VISIBLE,
  INDEX `rolId` (`rolId` ASC) VISIBLE,
  INDEX `genreId` (`genreId` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`addressId`)
    REFERENCES `jbikex`.`addresses` (`id`),
  CONSTRAINT `users_ibfk_2`
    FOREIGN KEY (`rolId`)
    REFERENCES `jbikex`.`rols` (`id`),
  CONSTRAINT `users_ibfk_3`
    FOREIGN KEY (`genreId`)
    REFERENCES `jbikex`.`genres` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `payment` VARCHAR(255) NULL DEFAULT NULL,
  `userId` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `jbikex`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`orderproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`orderproducts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `productId` INT(11) NULL DEFAULT NULL,
  `orderId` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `total` DECIMAL(10,0) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `orderId` (`orderId` ASC) VISIBLE,
  CONSTRAINT `orderproducts_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `jbikex`.`products` (`id`),
  CONSTRAINT `orderproducts_ibfk_2`
    FOREIGN KEY (`orderId`)
    REFERENCES `jbikex`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `jbikex`.`sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`sizes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jbikex`.`sizeproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbikex`.`sizeproducts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `productId` INT(11) NULL DEFAULT NULL,
  `sizeId` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `sizeId` (`sizeId` ASC) VISIBLE,
  CONSTRAINT `sizeproducts_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `jbikex`.`products` (`id`),
  CONSTRAINT `sizeproducts_ibfk_2`
    FOREIGN KEY (`sizeId`)
    REFERENCES `jbikex`.`sizes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
